### ISSUE TITLE
Cannot save edit because of simple-Schema

### ISSUE THREAD

**Issue by domgolonka** [JackAdams/meteor-editable-text#25] opened 2015-04-22 06:21 UTC
Exception while simulating the effect of invoking '_editableTextWrite' TypeError: Cannot read property 'simpleSchema' of undefined {stack: (...), message: "Cannot read property 'simpleSchema' of undefined"} TypeError: Cannot read property 'simpleSchema' of undefined
    at Meteor.methods._editableTextWrite (http://localhost:3000/packages/babrahams_editable-text.js?07c4e9224552dff65d6bf4ebcbe46ff408cd5770:840:96)
    at http://localhost:3000/packages/ddp.js?d1840d3ba04c65ffade261f362e26699b7509706:4269:25
    at _.extend.withValue (http://localhost:3000/packages/meteor.js?43b7958c1598803e94014f27f5f622b0bddc0aaf:955:17)
    at _.extend.apply (http://localhost:3000/packages/ddp.js?d1840d3ba04c65ffade261f362e26699b7509706:4260:54)
    at _groundUtil.Connection.apply (http://localhost:3000/packages/ground_db.js?02d5a5d038e85d67206767bd48d08764a8c94da1:998:31)
    at _.extend.call (http://localhost:3000/packages/ddp.js?d1840d3ba04c65ffade261f362e26699b7509706:4138:17)
    at Object.EditableText.update (http://localhost:3000/packages/babrahams_editable-text.js?07c4e9224552dff65d6bf4ebcbe46ff408cd5770:333:12)
    at Object.EditableText._makeUpdate (http://localhost:3000/packages/babrahams_editable-text.js?07c4e9224552dff65d6bf4ebcbe46ff408cd5770:499:27)
    at Object.EditableText.okCancelEvents.ok (http://localhost:3000/packages/babrahams_editable-text.js?07c4e9224552dff65d6bf4ebcbe46ff408cd5770:597:28)
    at Object.EditableText._okCancelEvents.events.(anonymous function) (http://localhost:3000/packages/babrahams_editable-text.js?07c4e9224552dff65d6bf4ebcbe46ff408cd5770:432:16)
editable_text.js:77

 Meteor.makeErrorType.errorClass {error: 500, reason: "Internal server error", details: undefined, message: "Internal server error [500]", errorType: "Meteor.Error"…}

**Comment by JackAdams** [comment] 2015-04-22 09:31
Sorry about that. Fixed in latest release.

If there's still a problem, check that the collection name in `collection="<your-collection-name>"` matches the collection name in mongodb.

**Comment by domgolonka** [comment] 2015-04-22 09:48
Thanks! But I am still getting the same error. The Collection is correct. EditableText is retrieving the information from the Collection, but it won't edit/save them.

**Comment by JackAdams** [comment] 2015-04-22 09:54
Okay. Very strange.  No chance it's a client-side only collection?

(What's happening is that the collection is not being detected correctly on the server, based on the collection name.)

Any chance of putting a minimal repro on meteorpad or github or something like that?

**Comment by domgolonka** [comment] 2015-04-22 10:33
Hey,

I created a meteorpad: http://meteorpad.com/pad/Mf4MiStZ6kdjSzAS2/Copy%20of%20Departments

**Comment by JackAdams** [comment] 2015-04-22 10:58
Thanks for the Meteorpad!

In your code on Meteorpad, you need `collection="departments"` rather than `collection="Department"`. See [this meteorpad](http://meteorpad.com/pad/rP46ddJ3mnTod7qaK/Copy%20of%20Departments%20%281%29) for a version with this change made.

The `collection` string must match the name of the collection as found in mongodb (not the name of the `Mongo.Collection` instance you define programatically).

**Closed as completed by JackAdams** 2015-04-22 10:58 UTC

**Comment by domgolonka** [comment] 2015-04-22 18:37
Thanks!

**Comment by rogchap** [comment] 2015-06-11 03:54
I was also getting this error, and none of the above solutions where the cause. 

I have all my collections created in a local package (which is shared across multiple meteor apps), therefore `dburles:mongo-collection-instances` (which is used by this package) has no affect on my collections, causing the above/similar error when calling `Mongo.Collection.get(<collection-name>)`

**Simple fix**: add `mongo-collection-instances` to my local package's `package.json`:

```
api.use('dburles:mongo-collection-instances');
```

Though I would add my 2¢ just incase someone else came across the same problem.

**Comment by JackAdams** [comment] 2015-06-11 04:32
@rogchap thank you for adding to this discussion. I think this warrants a separate issue of its own. Creating one now (#39). Hope you don't mind me lifting a quote directly from your comment above.

**Comment by sungwoncho** [comment] 2015-08-24 07:15
> The collection string must match the name of the collection as found in mongodb (not the name of the Mongo.Collection instance you define programatically).

@JackAdams I think this should be made clear in the README.

**Comment by JackAdams** [comment] 2015-08-24 07:29
@sungwoncho Agreed.  Will have that update in the next version.
